[project]
name = "deepseek-tools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "fufu", email = "fufurobot@outlook.com" }
]
requires-python = ">=3.13"
dependencies = [
    "jinja2>=3.1.6",
    "playwright>=1.58.0",
    "pynput>=1.8.1",
    "pyperclip>=1.11.0",
    "requests>=2.33.1",
]

[project.scripts]
clip-commit = "deepseek_tools.clip_commit:main"
concat-repo = "deepseek_tools.concat_repo:main"
auto-commit = "deepseek_tools.git_auto_commit:main"
git_cloner = "deepseek_tools.git_cloner:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
